spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false
  datasource:
    #url: jdbc:mysql://localhost:3306/mtprophet?enabledTLSProtocols=TLSv1.2
    url: jdbc:mysql://localhost:3306/MagiSystemDB?serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      encoding: utf-8
      